### ISSUE TITLE
Use PAGER environment variable instead of 'less'

### ISSUE THREAD

**Issue by notramo** [sharkdp/bat#158]
`bat` sould use pager name from `PAGER` environment variable, and only use `less` if `PAGER` is unset.

**Comment by sharkdp** [comment]
Good idea!

**Comment by sharkdp** [comment]
How would we handle command line arguments to the pager? Currently, we pass `--RAW-CONTROL-CHARS`, `--no-init` and (optionally) `--quit-if-one-screen`. We cannot expect other pagers to have the same command line options.

I guess the only option would be to pass no command-line arguments (can/should command-line arguments be specified in `$PAGER`?) if `$PAGER` is set. Also, we should check if `$PAGER == "less"` and fall back to using the normal command-line aguments.

**Comment by notramo** [comment]
I think, support should be added for each pager in `bat`, and fall back to no arguments if pager isn't supported.
For example, the [`slit`](https://github.com/tigrawap/slit) pager parses the 16 base colors by default (there is a [feature request](https://github.com/tigrawap/slit/issues/46) for xterm-256 colors) , and don't launch the curses interface if output fits in one screen, only prints it.

**Comment by moonfruit** [comment]
`bat` should add a **command line argument** to customize the pager **first**.
Only after that, we can discuss whether to support the environment variable `PAGER`.
And, maybe we can use a different environment variable, like `BAT_PAGER`.

**Comment by sharkdp** [comment]
@moonfruit `PAGER` seems to be supported by a lot of programs (`man`, `git`, `mysql`, .. to name a few). I think it's perfectly fine to support `PAGER` first and add overrides later, if we feel we need to.

**Comment by moonfruit** [comment]
@sharkdp You are right about that many programs support `PAGER`, but most of them also support another way to specific pager (command line argument or configuration file).
If I want to use a different pager for `bat` other than system pager, I cannot do it in case of that `bat` only support `PAGER` environment variable.

**Comment by notramo** [comment]
`git` also has the `GIT_PAGER` environment variable. I think this few lines of code shouldn't be a big problem.

**Comment by yaauie** [comment]
I think a reasonable detection would follow:

1. Use `BAT_PAGER` if present
2. else, use `PAGER` if present (optionally: skip this if `--no-detect-pager` command-line flag present)
3. else, fall back to current usage of `less` with bat-optimised flags

In either case that we use an environment variable, it would be convenient to support including flags for the pager (e.g., my personal `PAGER` is `less --no-init --quit-if-one-screen --chop-long-lines` which works well with `man` and other well-behaved posix built-ins, and it would be inconvenient if bat did not support flags)

**Comment by achalddave** [comment]
For those looking for a temporary alternative, I'm using an alias as follows. In my case, I wanted to pass the "-X" flag to `less` so that the contents of a long file are not kept on my screen after I quit the pager. 

```
if command -v bat >/dev/null ; then
    BAT_PATH=$(which bat)
    function bat() {
        if [ -t 1 ] ; then
            $BAT_PATH --color always --style full --paging never $* \
                | less --tabs 4 -RF
        else
            $BAT_PATH $*
        fi
    }
fi```

**Comment by sharkdp** [comment]
I have implemented a first version of this in #192. It'd be great if someone could review this.

**Comment by sharkdp** [comment]
Released in [bat 0.5](https://github.com/sharkdp/bat/releases/tag/v0.5.0).

**Comment by dharmeshkakadia** [comment]
I am running 0.6.0 and I am still not able to scroll in iTerm. Is there specific flag or something that I need to set?

**Comment by mike-mosher** [comment]
I'm using the default Terminal app in Mac, and the suggestion from achalddave in [the above comment](https://github.com/sharkdp/bat/issues/158#issuecomment-406735839) didn't work for me.

I modified the bash function to use RS instead of RF, and was able to get mouse scrolling to work:
```
if command -v bat >/dev/null ; then
    BAT_PATH=$(which bat)
    function bat() {
        if [ -t 1 ] ; then
            $BAT_PATH --color always --style full --paging never $* \
                | less --tabs 4 -RS
        else
            $BAT_PATH $*
        fi
    }
fi
```

**Comment by Inphi** [comment]
You can trick bat into passing no arguments to the pager (particularly less) by setting `BAT_PAGER="less --"`. This trick works well even for small files as an altscreen will be created.

**Comment by tavianator** [comment]
> How would we handle command line arguments to the pager? Currently, we pass `--RAW-CONTROL-CHARS`, `--no-init` and (optionally) `--quit-if-one-screen`. We cannot expect other pagers to have the same command line options.

`less` respects the environment variable `LESS`, so you could set that (if it's not already set) and just execute `$PAGER`.  That's what `git` does.

**Comment by sharkdp** [comment]
This issue is quite old. In the meantime we have a pager handling which is quite robust, I believe. 

We actually do interpret the command-line arguments in `PAGER`, but we make sure to always enable `-R`:

https://github.com/sharkdp/bat/blob/e9210c0f6c390ccffe72a5461c57b8348ceb4a48/src/output.rs#L31-L44
