### ISSUE TITLE
mouse scrolling doesn't work

### ISSUE THREAD

**Issue by gagan0723** [sharkdp/bat#556]
My `bat.config` is exactly the same as in https://github.com/sharkdp/bat#format.

I have gone through previous issues  #420, #188, #382, #193.

```bash
▶ [com/group10app] (bluetooth ⁚ $✘!+) bat --version         
bat 0.10.0
▶ [com/group10app] (bluetooth ⁚ $✘!+) bat --config-file
/Users/gagan/.config/bat/config
```

### Config
```bash
# Set the theme to "TwoDark"
--theme="OneHalfDark"

# Show line numbers, Git modifications and file header (but no grid)
--style="numbers,changes,header,grid"

# Use italic text on the terminal (not supported on all terminals)
--italic-text=always

# Add mouse scrolling support in less (does not work with older
# versions of "less")
--pager="less -FR"

# Use C++ syntax (instead of C) for .h header files
--map-syntax h:cpp

# Use "gitignore" highlighting for ".ignore" files
--map-syntax .ignore:.gitignore
```

### System
```bash
macOS Mojave
Version: 10.14.4 
```

**Comment by gagan0723** [comment]
Thanks, @dc2. `export BAT_PAGER="less -RF"` works fine. I will leave this open until this gets fixed.

And thanks to **David Peter** and the community for the hard work.

**Comment by gagan0723** [comment]
Thanks for the update. I will close this issue and wait for the release.

See #509.

**Comment by sharkdp** [comment]
Fixed in [v0.11.0](https://github.com/sharkdp/bat/releases/tag/v0.11.0).

**Comment by gagan0723** [comment]
@sharkdp, this issues still exists in the latest version with the same confi as above. I also tried addign `-S` flag but that didn't help. Right now I am using `export BAT_PAGER="less -RF"`.

I am sure the `less` version is the latest.
```bash
▶ [fork/xray] (master ⁚ ) (🦀 v1.33.0-nightly) less --version
less 530 (PCRE regular expressions)
Copyright (C) 1984-2017  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less

▶ [fork/xray] (master ⁚ ) (🦀 v1.33.0-nightly) brew info less        
less: stable 530 (bottled)
Pager program similar to more
http://www.greenwoodsoftware.com/less/index.html
/usr/local/Cellar/less/530_1 (12 files, 336.2KB) *
  Poured from bottle on 2019-06-15 at 00:45:49
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/less.rb
==> Dependencies
Required: pcre ✔
==> Analytics
install: 701 (30 days), 2,248 (90 days), 10,816 (365 days)
install_on_request: 670 (30 days), 2,104 (90 days), 9,976 (365 days)
build_error: 0 (30 days)
```

**Comment by sharkdp** [comment]
I can not reproduce this anymore. Could you please post the output of this script:

``` bash
set -x

alias bat
bat --version
bat --config-file
bat --cache-dir
less --version

bat "$(bat --config-file)"
ls "$(bat --cache-dir)"

set +x

echo "BAT_PAGER = '$BAT_PAGER'"
echo "BAT_CONFIG_PATH = '$BAT_CONFIG_PATH'"
echo "BAT_STYLE = '$BAT_STYLE'"
echo "BAT_THEME = '$BAT_THEME'"
echo "BAT_TABS = '$BAT_TABS'"
echo "PAGER = '$PAGER'"
echo "LESS = '$LESS'"
```

**Comment by gagan0723** [comment]
I have got it working by replacing `BAT_CONFIG_PATH` that is ` '~/.dotfiles/bat/bat.conf'` with `/Users/gagan/.dotfiles/bat/bat.conf`.

### Shouldn't it work with `'~/.dotfiles/bat/bat.conf'` as well?

Below is the output:

```bash
Last login: Sat Jun 15 15:48:50 on ttys000

▶ [~] bat "$(bat --config-file)"
[bat error]: '/Users/gagan/.config/bat/config': No such file or directory (os error 2)

▶ [~] bat --config-file         
/Users/gagan/.config/bat/config

▶ [~] echo "BAT_CONFIG_PATH = '$BAT_CONFIG_PATH'"
BAT_CONFIG_PATH = '~/.dotfiles/bat/bat.conf'

▶ [~] sconf # for sourcing config file

▶ [~] bat "$(bat --config-file)"                 
───────┬────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /Users/gagan/.dotfiles/bat/bat.conf
───────┼────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # Set the theme to "TwoDark"
   2   │ --theme="OneHalfDark"
   3   │ 
   4   │ # Show line numbers, Git modifications and file header (but no grid)
   5   │ --style="numbers,changes,header,grid"
   6   │ 
   7   │ # Use italic text on the terminal (not supported on all terminals)
   8   │ --italic-text=always
   9   │ 
  10   │ # Add mouse scrolling support in less (does not work with older
  11   │ # versions of "less")
  12   │ --pager="less -FR"
  13   │ 
  14   │ # Use C++ syntax (instead of C) for .h header files
  15   │ --map-syntax h:cpp
  16   │ 
  17   │ # Use "gitignore" highlighting for ".ignore" files
  18   │ --map-syntax .ignore:.gitignore
───────┴────────────────────────────────────────────────────────────────────────────────────────────

▶ [~] bat --config-file                          
/Users/gagan/.dotfiles/bat/bat.conf

▶ [~] echo "BAT_CONFIG_PATH = '$BAT_CONFIG_PATH'"
BAT_CONFIG_PATH = '/Users/gagan/.dotfiles/bat/bat.conf'

▶ [~] 
```

**Comment by sharkdp** [comment]
> Shouldn't it work with `'~/.dotfiles/bat/bat.conf'` as well?

I don't think so. `~` is a shell builtin and not an actual path. Once you escape it (`ls '~'` or `find '~'`), it's not typically parsed as "home directory".

**Comment by theimpostor** [comment]
FWIW I got mouse support working on macos by installing the homebrew version of less (`brew install less`) which is much newer than the version that ships with mac by default. I did not need to adjust any bat config settings.

Perhaps the bat homebrew formula could list less as a dependency?

**Comment by sharkdp** [comment]
> FWIW I got mouse support working on macos by installing the homebrew version of less (`brew install less`) which is much newer than the version that ships with mac by default. I did not need to adjust any bat config settings.

Yes, that's a new feature in [`bat` 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0): *"Do not pass '--no-init' on newer less versions, see #749 and #786 (@sharkdp)*"

> Perhaps the bat homebrew formula could list less as a dependency?

That should be discussed on the homebrew repository, but it sounds like a reasonable request to me.
