### ISSUE TITLE
syntax highlight for markdown code block

### ISSUE THREAD

**Issue by laoshaw** [sharkdp/bat#963]
I like the way bat highlight most file types, markdown is one of the most commonly used and if bat supports highlighting of its code block that will be great.

**Comment by sharkdp** [comment]
That should work out of the box. Have you seen the first screenshot in the README?

**Comment by laoshaw** [comment]
Yes there are some highlighting, it looks much bare-bone comparing to the original code though, actually too bare-bone.

cp test.py test.md
vi test.md to make it surrounded by python code block tags, ` ```python ``` `
bat test.py -- nicely highlighted
bat test.md -- barely highlighted

**Comment by sharkdp** [comment]
You are right. That's actually a regression in bat 0.13.0. It used to work fine before.

**Comment by sharkdp** [comment]
And this is the commit that broke the Markdown syntax for us: https://github.com/sublimehq/Packages/commit/c08f85346a04d2e12990c3008e7666306b59a05b

**Comment by sharkdp** [comment]
Temporarily fixed by patching the Markdown syntax.

**Comment by sharkdp** [comment]
Fix released in [v0.15.1](https://github.com/sharkdp/bat/releases/tag/v0.15.1)

**Comment by rayntriton** [comment]
Bug persists at compile from source.
Tested on a ```md``` file with ```js``` and ```clj``` . The ```clj``` part is not highlighted.
p.d. Thank you for bat

**Comment by sharkdp** [comment]
@rayntriton That is a separate issue. Maybe related to #2084
